import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import MSWProvider from "@/app/MSWProvider";

// Use the fonts generated by v0 for the correct UI layout
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "VertexAI · SOC Dashboard",
  description:
    "VertexAI human-supervised multi-agent cybersecurity platform. " +
    "Risk prioritization, deduplication, and HITL vulnerability management.",
  icons: {
    icon: [
      {
        url: "/icon-light-32x32.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/icon-dark-32x32.png",
        media: "(prefers-color-scheme: dark)",
      },
      {
        url: "/icon.svg",
        type: "image/svg+xml",
      },
    ],
    apple: "/apple-icon.png",
  },
};

export const viewport: Viewport = {
  colorScheme: "light dark",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} bg-background`}
    >
      <body className="antialiased font-sans">
        {/* MSWProvider activates Mock Service Worker in development only.
            Remove this wrapper at Integration Step 3 when pointing at the
            real Spring Boot backend (NEXT_PUBLIC_API_URL=http://localhost:8080). */}
        <MSWProvider>
          {children}
        </MSWProvider>
      </body>
    </html>
  );
}