/**
 * VertexAI / SentinelAI — TypeScript Data Contracts
 *
 * AUTHORITATIVE SOURCE: integration_plan.md §5
 * All field names are frozen and must not be renamed.
 * Any deviation from this schema is a CONFLICT against the integration contract.
 */

// ---------------------------------------------------------------------------
// Pipeline Status (scan_jobs.status)
// Source: implementation_guide.md §4 — Conceptual Pipeline States
// ---------------------------------------------------------------------------
export type PipelineStatus =
  | 'PENDING'
  | 'RUNNING'
  | 'WAITING_FOR_HUMAN'
  | 'COMPLETED'
  | 'STOPPED'
  | 'FAILED';

// ---------------------------------------------------------------------------
// Priority Level (risk_scores.priority_level)
// Source: integration_plan.md §5 — SLA tiers
// ---------------------------------------------------------------------------
export type PriorityLevel =
  | 'P0_CRITICAL'
  | 'P1_HIGH'
  | 'P2_MEDIUM'
  | 'P3_LOW';

// ---------------------------------------------------------------------------
// Scanner Sources (canonical_vulnerabilities.scanner_sources)
// ---------------------------------------------------------------------------
export type ScannerSource = 'NMAP' | 'NUCLEI' | 'OWASP_ZAP' | 'OPENVAS';

// ---------------------------------------------------------------------------
// CanonicalFinding — FROZEN CONTRACT (16 fields)
// Source: integration_plan.md §5
// Shared identically by Team 1 (persists/returns it), Team 2 (produces it),
// and Team 3 (renders it). Do NOT rename, add, or remove fields.
// ---------------------------------------------------------------------------
export interface CanonicalFinding {
  /** UUID primary key from canonical_vulnerabilities.finding_id */
  finding_id: string;

  /** MD5(target_host + ":" + target_port + ":" + cve_id + ":" + endpoint_path) */
  fingerprint_hash: string;

  /** CVE identifier, e.g. "CVE-2021-44228" */
  cve_id: string;

  /** Human-readable vulnerability name */
  vulnerability_name: string;

  /** Hostname or IP address of the scanned target */
  target_host: string;

  /** TCP/UDP port number on the target */
  target_port: number;

  /** Array of scanner tools that reported this finding */
  scanner_sources: ScannerSource[];

  /**
   * XGBoost false-positive probability (0.0 – 1.0).
   * If > 0.85, is_suppressed is set to true by Agent 2.
   */
  false_positive_prob: number;

  /** True when false_positive_prob > 0.85 — suppressed by Agent 2 */
  is_suppressed: boolean;

  /** True when an analyst has accepted this as an accepted risk */
  is_accepted_risk: boolean;

  /** True when this CVE appears in the CISA Known Exploited Vulnerabilities catalog */
  is_cisa_kev: boolean;

  /**
   * FIRST.org EPSS score (0.0 – 1.0): 30-day exploit probability.
   * Source: https://api.first.org/data/v1/epss?cve=CVE-XXX
   */
  epss_score: number;

  /**
   * Agent 4 composite risk score (0.0 – 100.0).
   * Formula: (CVSS × 0.30) + (EPSS × 10 × 0.35) + KEV_Bonus + (Asset_Criticality × 4.0)
   * KEV_Bonus = +25.0 if is_cisa_kev else 0.0
   */
  composite_risk_score: number;

  /**
   * Priority tier derived from composite_risk_score.
   * P0_CRITICAL: 80–100 → 24h SLA
   * P1_HIGH:     60–79.9 → 72h SLA
   * P2_MEDIUM:   40–59.9 → 14d SLA
   * P3_LOW:      0–39.9  → 30d SLA
   */
  priority_level: PriorityLevel;

  /** ISO-8601 timestamp deadline for remediation */
  sla_deadline: string;

  /**
   * Natural-language explanation of the composite risk score.
   * Generated by Agent 4's rule-assisted LLM/template explainer.
   */
  explainable_rationale: string;
}

// ---------------------------------------------------------------------------
// Dashboard Metrics — GET /api/dashboard response
// Source: architecture_plan.md §11, integration_plan.md §4
// ---------------------------------------------------------------------------
export interface DashboardMetrics {
  /** Aggregate security score 0–100 (e.g. 96) — must be sourced from API, never hardcoded */
  security_score: number;

  /** Total number of canonical findings in the current scan */
  total_findings: number;

  /** Subset of total_findings that are not suppressed */
  active_findings: number;

  /** Number of findings with is_suppressed = true */
  suppressed_findings: number;

  /** Noise reduction percentage: (suppressed / raw_count) × 100 */
  noise_reduction_rate: number;

  /** Top-priority threats for the dashboard summary panel */
  top_threats: CanonicalFinding[];

  /** Current pipeline status */
  pipeline_status: PipelineStatus;
}

// ---------------------------------------------------------------------------
// Asset — maps to the assets table (Team 1 entity)
// ---------------------------------------------------------------------------
export interface Asset {
  asset_id: string;
  hostname: string;
  ip_address: string;
  environment: 'PRODUCTION' | 'STAGING' | 'DEV';
  criticality_rating: 1 | 2 | 3 | 4 | 5;
  owner_email: string;
  is_authorized: boolean;
  created_at: string;
}

// ---------------------------------------------------------------------------
// ScanJob — maps to the scan_jobs table (Team 1 entity)
// ---------------------------------------------------------------------------
export interface ScanJob {
  scan_id: string;
  asset_id: string;
  status: PipelineStatus;
  scanners_used: string;
  started_at: string;
  completed_at: string | null;
  /** Current agent output, structure agreed between Team 1 and Team 3 */
  agent_output?: AgentOutput | null;
}

// ---------------------------------------------------------------------------
// AgentOutput — structure of GET /api/scans/{id} agent_output field
// OPEN DECISION: exact shape pending Team 1 / Team 3 agreement (integration_plan.md OPEN #5)
// ---------------------------------------------------------------------------
export interface AgentOutput {
  stage: 1 | 2 | 3 | 4;
  findings?: CanonicalFinding[];
  message?: string;
}

// ---------------------------------------------------------------------------
// HITL Control — POST /api/scans/{id}/control request body
// Source: integration_plan.md §4
// ---------------------------------------------------------------------------
export interface HITLControl {
  action: 'CONTINUE' | 'STOP';
}

// ---------------------------------------------------------------------------
// TicketPayload — POST /api/vulnerabilities/{id}/ticket
// Source: integration_plan.md §4 — Final Human Approval
// ---------------------------------------------------------------------------
export interface TicketApprovalRequest {
  approved: true;
}

export interface TicketApprovalResponse {
  ticket_url: string;
  status: string;
}

// ---------------------------------------------------------------------------
// WebSocket Message — ws://localhost:8080/ws/pipeline
// Source: integration_plan.md §9
// OPEN DECISION: exact message shape pending Team 1 / Team 3 agreement (integration_plan.md OPEN #4)
// ---------------------------------------------------------------------------
export interface WebSocketMessage {
  scan_id: string;
  status: PipelineStatus;
  stage?: number;
  message?: string;
  timestamp: string;
}
