import uuid
from datetime import datetime, timedelta, timezone
from fastapi import APIRouter
from pydantic import BaseModel
from typing import List, Optional

router = APIRouter(prefix="/api/v1/agent4")

class EnrichedFinding(BaseModel):
    finding_id: str
    fingerprint_hash: str
    cve_id: str
    vulnerability_name: str
    target_host: str
    target_port: int
    cvss_base_score: float
    scanner_sources: List[str]
    false_positive_prob: float
    is_suppressed: bool
    is_accepted_risk: bool
    is_cisa_kev: bool = False
    epss_score: float = 0.0
    epss_percentile: float = 0.0
    exploit_db_available: bool = False

class AssetContext(BaseModel):
    asset_id: str
    hostname: str
    criticality_rating: int
    environment: str = "PRODUCTION"

class ScoreRequest(BaseModel):
    findings: List[EnrichedFinding]
    asset_context: AssetContext

class ScoredFinding(BaseModel):
    finding_id: str
    fingerprint_hash: str
    cve_id: str
    vulnerability_name: str
    target_host: str
    target_port: int
    cvss_base_score: float
    scanner_sources: List[str]
    false_positive_prob: float
    is_suppressed: bool
    is_accepted_risk: bool
    is_cisa_kev: bool
    epss_score: float
    composite_risk_score: Optional[float] = None
    priority_level: Optional[str] = None
    sla_deadline: Optional[str] = None
    explainable_rationale: Optional[str] = None

class TicketPayload(BaseModel):
    finding_id: str
    title: str
    body: str
    labels: List[str]
    assignee: Optional[str] = None
    priority_level: str
    sla_deadline: str
    composite_risk_score: float

class ScoreResponse(BaseModel):
    status: str = "WAITING_FOR_HUMAN"
    scored_findings: List[ScoredFinding]
    ticket_payloads: List[TicketPayload]

def compute_composite_risk_score(cvss: float, epss: float, is_kev: bool, asset_criticality: int) -> float:
    kev_bonus = 25.0 if is_kev else 0.0
    score = (cvss * 0.30) + (epss * 10 * 0.35) + kev_bonus + (asset_criticality * 4.0)
    return min(score, 100.0)

def assign_priority_and_sla(score: float) -> tuple[str, str]:
    now = datetime.now(timezone.utc)
    if score >= 80.0:
        return "P0_CRITICAL", (now + timedelta(hours=24)).isoformat()
    elif score >= 60.0:
        return "P1_HIGH", (now + timedelta(hours=72)).isoformat()
    elif score >= 40.0:
        return "P2_MEDIUM", (now + timedelta(days=14)).isoformat()
    else:
        return "P3_LOW", (now + timedelta(days=30)).isoformat()

def generate_rationale(finding: EnrichedFinding, score: float, priority: str, asset_context: AssetContext) -> str:
    parts = []
    parts.append(f"Composite Risk Score: {score:.1f}/100.0 [{priority}]")
    parts.append(f"CVSS Base Score: {finding.cvss_base_score}/10.0 (contributes {finding.cvss_base_score * 0.30:.1f} points)")
    parts.append(f"EPSS Score: {finding.epss_score:.4f} (contributes {finding.epss_score * 10 * 0.35:.1f} points)")
    if finding.is_cisa_kev:
        parts.append("CISA KEV: Listed in Known Exploited Vulnerabilities catalog (+25.0 points)")
    else:
        parts.append("CISA KEV: Not listed (+0.0 points)")
    parts.append(f"Asset Criticality: {asset_context.criticality_rating}/5 (contributes {asset_context.criticality_rating * 4.0:.1f} points)")
    parts.append(f"Asset: {asset_context.hostname} ({asset_context.environment})")
    parts.append(f"Scanners: {', '.join(finding.scanner_sources)}")
    if finding.is_suppressed:
        parts.append("Note: This finding was flagged as a likely false positive.")
    if finding.is_accepted_risk:
        parts.append("Note: This finding has been marked as accepted risk.")
    return " | ".join(parts)

def generate_ticket_body(finding: EnrichedFinding, score: float, priority: str, sla: str, rationale: str, asset_context: AssetContext) -> str:
    body = f"""## Security Vulnerability Report

**CVE:** {finding.cve_id}
**Vulnerability:** {finding.vulnerability_name}
**Target:** {finding.target_host}:{finding.target_port}
**CVSS:** {finding.cvss_base_score}
**Composite Risk Score:** {score:.1f}/100.0
**Priority:** {priority}
**SLA Deadline:** {sla}
**Asset:** {asset_context.hostname} (Criticality: {asset_context.criticality_rating}/5, Environment: {asset_context.environment})

### Risk Analysis
{rationale}

### Scanner Sources
{', '.join(finding.scanner_sources)}

### CISA KEV Status
{'⚠️ Listed in CISA Known Exploited Vulnerabilities catalog' if finding.is_cisa_kev else 'Not listed'}

### EPSS Score
{finding.epss_score:.4f} ({finding.epss_score * 100:.1f}% probability of exploitation in next 30 days)

---
*Generated by VertexAI Agent 4 — Risk Scoring & Ticket Preparation*
*This ticket was prepared for human review. It has NOT been auto-dispatched.*"""
    return body

@router.post("/score-and-ticket", response_model=ScoreResponse)
async def score_and_ticket(request: ScoreRequest):
    scored_findings = []
    ticket_payloads = []

    for finding in request.findings:
        if finding.is_suppressed or finding.is_accepted_risk:
            # Include without score/ticket
            scored_findings.append(ScoredFinding(
                finding_id=finding.finding_id,
                fingerprint_hash=finding.fingerprint_hash,
                cve_id=finding.cve_id,
                vulnerability_name=finding.vulnerability_name,
                target_host=finding.target_host,
                target_port=finding.target_port,
                cvss_base_score=finding.cvss_base_score,
                scanner_sources=finding.scanner_sources,
                false_positive_prob=finding.false_positive_prob,
                is_suppressed=finding.is_suppressed,
                is_accepted_risk=finding.is_accepted_risk,
                is_cisa_kev=finding.is_cisa_kev,
                epss_score=finding.epss_score
            ))
            continue
            
        score = compute_composite_risk_score(
            finding.cvss_base_score,
            finding.epss_score,
            finding.is_cisa_kev,
            request.asset_context.criticality_rating
        )
        
        priority, sla = assign_priority_and_sla(score)
        rationale = generate_rationale(finding, score, priority, request.asset_context)
        
        scored_findings.append(ScoredFinding(
            finding_id=finding.finding_id,
            fingerprint_hash=finding.fingerprint_hash,
            cve_id=finding.cve_id,
            vulnerability_name=finding.vulnerability_name,
            target_host=finding.target_host,
            target_port=finding.target_port,
            cvss_base_score=finding.cvss_base_score,
            scanner_sources=finding.scanner_sources,
            false_positive_prob=finding.false_positive_prob,
            is_suppressed=finding.is_suppressed,
            is_accepted_risk=finding.is_accepted_risk,
            is_cisa_kev=finding.is_cisa_kev,
            epss_score=finding.epss_score,
            composite_risk_score=score,
            priority_level=priority,
            sla_deadline=sla,
            explainable_rationale=rationale
        ))
        
        ticket_body = generate_ticket_body(finding, score, priority, sla, rationale, request.asset_context)
        
        sla_hours = 24 if priority == "P0_CRITICAL" else (72 if priority == "P1_HIGH" else (336 if priority == "P2_MEDIUM" else 720))
        sla_label = f"sla-{sla_hours}h"
        
        ticket_payloads.append(TicketPayload(
            finding_id=finding.finding_id,
            title=f"[{priority}] {finding.cve_id} - {finding.vulnerability_name} on {finding.target_host}:{finding.target_port}",
            body=ticket_body,
            labels=[priority, "security", sla_label],
            assignee=None,
            priority_level=priority,
            sla_deadline=sla,
            composite_risk_score=score
        ))

    return ScoreResponse(
        status="WAITING_FOR_HUMAN",
        scored_findings=scored_findings,
        ticket_payloads=ticket_payloads
    )
