import pytest
import json
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

def test_health_endpoint():
    """Verify health endpoint."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "UP", "service": "python-agents"}

def test_full_pipeline_end_to_end():
    """Verify full pipeline flow:
    Agent 1 (Parse) -> Agent 2 (Deduplicate) -> Agent 3 (Enrich) -> Agent 4 (Score & Ticket)
    """
    # 1. Agent 1: Parse multi-scanner reports
    zap_report = json.dumps({
        "site": [{
            "alerts": [{
                "name": "Apache Log4j RCE",
                "riskcode": "3",
                "confidence": "3",
                "cweid": "502",
                "otherinfo": "CVE-2021-44228 detected in authorization header",
                "instances": [
                    {"uri": "https://192.168.1.50:8443/auth/login"},
                    {"uri": "https://192.168.1.50:8443/auth/login"}
                ]
            }]
        }]
    })

    nuclei_report = json.dumps({
        "template-id": "cve-2021-44228",
        "info": {
            "name": "Apache Log4j RCE",
            "severity": "critical",
            "classification": {"cve-id": ["CVE-2021-44228"]}
        },
        "host": "192.168.1.50",
        "matched-at": "https://192.168.1.50:8443/auth/login"
    })

    r1 = client.post("/api/v1/agent1/parse", json={
        "reports": [
            {"scanner_type": "OWASP_ZAP", "content": zap_report},
            {"scanner_type": "NUCLEI", "content": nuclei_report}
        ]
    })
    assert r1.status_code == 200
    p1_data = r1.json()
    assert p1_data["status"] == "WAITING_FOR_HUMAN"
    assert len(p1_data["findings"]) == 3  # 2 ZAP + 1 Nuclei

    # 2. Agent 2: Deduplicate & XGBoost FP Reduction
    r2 = client.post("/api/v1/agent2/reduce-noise", json={"findings": p1_data["findings"]})
    assert r2.status_code == 200
    p2_data = r2.json()
    assert p2_data["status"] == "WAITING_FOR_HUMAN"
    assert p2_data["statistics"]["input_count"] == 3
    assert p2_data["statistics"]["output_count"] == 1  # 3 duplicates merged to 1
    assert p2_data["statistics"]["duplicate_reduction_pct"] > 60.0
    assert len(p2_data["findings"]) == 1
    canonical = p2_data["findings"][0]
    assert set(canonical["scanner_sources"]) == {"OWASP_ZAP", "NUCLEI"}

    # 3. Agent 3: Threat Intelligence Enrichment
    r3 = client.post("/api/v1/agent3/enrich", json={"findings": p2_data["findings"]})
    assert r3.status_code == 200
    p3_data = r3.json()
    assert p3_data["status"] == "WAITING_FOR_HUMAN"
    assert len(p3_data["findings"]) == 1
    enriched = p3_data["findings"][0]
    assert enriched["cve_id"] == "CVE-2021-44228"
    assert enriched["is_cisa_kev"] is True
    assert enriched["epss_score"] > 0.9

    # 4. Agent 4: Risk Scoring & Ticket Preparation
    r4 = client.post("/api/v1/agent4/score-and-ticket", json={
        "findings": p3_data["findings"],
        "asset_context": {
            "asset_id": "asset-12345",
            "hostname": "prod-auth.corp",
            "criticality_rating": 5,
            "environment": "PRODUCTION"
        }
    })
    assert r4.status_code == 200
    p4_data = r4.json()
    assert p4_data["status"] == "WAITING_FOR_HUMAN"
    assert len(p4_data["scored_findings"]) == 1
    assert len(p4_data["ticket_payloads"]) == 1

    scored = p4_data["scored_findings"][0]
    assert scored["composite_risk_score"] > 50.0
    assert scored["priority_level"] in ["P0_CRITICAL", "P1_HIGH", "P2_MEDIUM", "P3_LOW"]

    ticket = p4_data["ticket_payloads"][0]
    assert "CVE-2021-44228" in ticket["title"]
    assert "Generated by VertexAI Agent 4" in ticket["body"]
    assert "This ticket was prepared for human review" in ticket["body"]
